package ${package}.domain.mapper;

import ${package}.domain.pojo.DemoBiz;
import ${package}.domain.pojo.DemoBizExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoBizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int countByExample(DemoBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int deleteByExample(DemoBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int insert(DemoBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int insertSelective(DemoBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    List<DemoBiz> selectByExample(DemoBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    DemoBiz selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DemoBiz record, @Param("example") DemoBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DemoBiz record, @Param("example") DemoBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemoBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_BIZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DemoBiz record);
}